first pass at refactor to use http api
mozilla-iam/cis_hris_publisher pull request #8
Opened 2018-01-25 20:19 UTC by andrewkrug

2018-01-25 20:48 UTC, gdestuynder requested changes

2018-01-25 20:48 UTC, gdestuynder commented on hris_publisher/prod-vars.yml
> +LDAP_NAMESPACE: Mozilla-LDAP-Dev
`Mozilla-LDAP` for prod

2018-01-25 20:55 UTC, andrewkrug commented on hris_publisher/prod-vars.yml
> +LDAP_NAMESPACE: Mozilla-LDAP-Dev
I caught that as well.

2018-01-26 18:19 UTC, gdestuynder approved these changes

2018-01-31 16:29 UTC, merged